services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/:/app
    ports:
      - 5173:5173
    command: sh -c "bun install && bun run dev"

  backend:
    image: cosmtrek/air
    working_dir: /app
    volumes:
      - ./backend/:/app

volumes:
  caddy_data:
  caddy_config:
