services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
    - 8081:8080

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /backend/node_modules
    ports:
      - 8080:8080
    depends_on:
    - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/:/app
    command: sh -c "bun install && bun run dev"
    ports:
      - 5173:5173

volumes:
  caddy_data:
  caddy_config:
