services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /backend/node_modules
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/:/app
    command: sh -c "bun install && bun run dev"
    ports:
      - 5173:5173

volumes:
  caddy_data:
  caddy_config:
