services:
  caddy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file: .env.development
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .svelte-kit/
            - build/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - pb_data:/pb/pb_data
      - pb_migrations:/pb/pb_migrations

volumes:
  pb_data:
  pb_migrations:
