/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OmOsRouteImport } from './routes/om-os'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthApprovalRouteImport } from './routes/auth/approval'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees/index'
import { Route as AdminEmployeesCreateRouteImport } from './routes/admin/employees/create'
import { Route as AdminEmployeesEmployeeIdRouteImport } from './routes/admin/employees/$employeeId'

const OmOsRoute = OmOsRouteImport.update({
  id: '/om-os',
  path: '/om-os',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthApprovalRoute = AuthApprovalRouteImport.update({
  id: '/auth/approval',
  path: '/auth/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesCreateRoute = AdminEmployeesCreateRouteImport.update({
  id: '/employees/create',
  path: '/employees/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesEmployeeIdRoute =
  AdminEmployeesEmployeeIdRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/om-os': typeof OmOsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/approval': typeof AuthApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/create': typeof AdminEmployeesCreateRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/om-os': typeof OmOsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/approval': typeof AuthApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/create': typeof AdminEmployeesCreateRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/menu': typeof MenuRoute
  '/om-os': typeof OmOsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/auth/approval': typeof AuthApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRoute
  '/admin/employees/create': typeof AdminEmployeesCreateRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kontakt'
    | '/menu'
    | '/om-os'
    | '/admin/dashboard'
    | '/auth/approval'
    | '/auth/login'
    | '/admin/employees/$employeeId'
    | '/admin/employees/create'
    | '/admin/employees'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/kontakt'
    | '/menu'
    | '/om-os'
    | '/admin/dashboard'
    | '/auth/approval'
    | '/auth/login'
    | '/admin/employees/$employeeId'
    | '/admin/employees/create'
    | '/admin/employees'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kontakt'
    | '/menu'
    | '/om-os'
    | '/admin/dashboard'
    | '/auth/approval'
    | '/auth/login'
    | '/admin/employees/$employeeId'
    | '/admin/employees/create'
    | '/admin/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  MenuRoute: typeof MenuRoute
  OmOsRoute: typeof OmOsRoute
  AuthApprovalRoute: typeof AuthApprovalRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/om-os': {
      id: '/om-os'
      path: '/om-os'
      fullPath: '/om-os'
      preLoaderRoute: typeof OmOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/approval': {
      id: '/auth/approval'
      path: '/auth/approval'
      fullPath: '/auth/approval'
      preLoaderRoute: typeof AuthApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/create': {
      id: '/admin/employees/create'
      path: '/employees/create'
      fullPath: '/admin/employees/create'
      preLoaderRoute: typeof AdminEmployeesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/$employeeId': {
      id: '/admin/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesEmployeeIdRoute: typeof AdminEmployeesEmployeeIdRoute
  AdminEmployeesCreateRoute: typeof AdminEmployeesCreateRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesEmployeeIdRoute: AdminEmployeesEmployeeIdRoute,
  AdminEmployeesCreateRoute: AdminEmployeesCreateRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  KontaktRoute: KontaktRoute,
  MenuRoute: MenuRoute,
  OmOsRoute: OmOsRoute,
  AuthApprovalRoute: AuthApprovalRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
