name: Publish Backend

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: backend

on:
  pull_request:
    branches: ["main", "dev", "edge"]
    paths:
      - "backend/**"
      - ".github/workflows/publish-backend.yaml"

  push:
    branches: ["main", "dev", "edge"]
    paths:
      - "backend/**"
      - ".github/workflows/publish-backend.yaml"

jobs:
  publish-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Publish Backend
        uses: mattismoel/actions/deploy@main
        with:
          context: ./backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_name: backend
